import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowLeft, BookOpen, Check, ChevronDown, ExternalLink, FlaskConical, Headphones, MapPin, MessageCircle, Package, RefreshCcw, ShieldCheck, Truck, Zap } from 'lucide-react';
import { Link, useParams } from 'wouter';
import type { StoreProduct } from '@workspace/api-client-react';
import { useStore } from '@/lib/store';
import { Breadcrumbs, CTASection, CatalogError, LoadingCatalog, PageHeading } from '@/components/page-parts';
import { ProductGrid } from '@/components/catalog-ui';

function PageMeta({ title, description }: { title: string; description: string }) {
  useEffect(() => {
    document.title = `${title} | CABL`;
    const meta = document.querySelector('meta[name="description"]') as HTMLMetaElement | null;
    if (meta) meta.content = description;
  }, [title, description]);
  return null;
}

function EditorialSection({ eyebrow, title, children }: { eyebrow?: string; title: string; children: ReactNode }) {
  return <section className="editorial-section"><div className="container"><div className="editorial-heading">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{children}</div></section>;
}

function InfoCards({ items }: { items: Array<{ icon: ReactNode; title: string; text: string; href?: string }> }) {
  return <div className="info-card-grid">{items.map((item) => <div className="info-card" key={item.title}><span className="info-card-icon">{item.icon}</span><h3>{item.title}</h3><p>{item.text}</p>{item.href && <Link href={item.href} className="text-link">اقرأ المزيد <ArrowLeft size={14}/></Link>}</div>)}</div>;
}

function FAQList({ items }: { items: Array<{ question: string; answer: string }> }) {
  return <div className="faq-list">{items.map((item) => <details className="faq-item" key={item.question}><summary>{item.question}<ChevronDown size={16}/></summary><p>{item.answer}</p></details>)}</div>;
}

function EditorialHero({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: ReactNode }) {
  return <div className="editorial-hero"><div className="container"><Breadcrumbs items={[{ label: title }]}/><div className="editorial-hero-copy"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p>{children}</div></div></div>;
}

export function AboutPage() {
  const { catalog } = useStore();
  const brands = Array.from(new Set((catalog?.products || []).map((product) => product.brand))).slice(0, 4);
  return <><PageMeta title="من نحن" description="تعرف على CABL وطريقة اختيار المنتجات وخدمة العملاء في اليمن."/><EditorialHero eyebrow="CABL / اليمن" title="من نحن" description="متجر إلكتروني يختار إكسسوارات الشحن والطاقة والصوتيات بعناية، ويعرض معلومات الشراء بوضوح للعملاء في اليمن."/><EditorialSection eyebrow="المهمة" title="اختيار أوضح ليومك"><InfoCards items={[{ icon: <ShieldCheck/>, title: 'بيانات منتج واضحة', text: 'العلامة والموديل والسعر والتوافر تظهر قبل أن تضيف المنتج إلى السلة.' }, { icon: <Zap/>, title: 'مواصفات مفيدة', text: 'نشرح القدرة والمنافذ والتوافق بلغة عملية، ولا نحوّل رقم الواط إلى وعد غير مؤكد.' }, { icon: <Truck/>, title: 'خطوات شراء مفهومة', text: 'الشحن والدفع والطلب تظهر في نفس المسار قبل التأكيد.' }, { icon: <MessageCircle/>, title: 'متابعة بعد الطلب', text: 'احتفظ برقم الطلب واستخدم صفحة التتبع عند الحاجة.' , href: '/orders' } ]}/></EditorialSection><EditorialSection title="علاقتنا بالعلامات التجارية"><div className="editorial-copy"><p>CABL متجر تجزئة مستقل. نعرض العلامة ورقم الموديل كما يردان في الكتالوج المنشور، ولا نخلط بين وجود المنتج في المتجر وبين ادعاء الوكالة أو الضمان المصنّع ما لم تظهر معلومة موثقة في صفحة المنتج.</p><p>أسماء العلامات والشعارات مملوكة لأصحابها وتستخدم لتعريف المنتجات المتاحة في الكتالوج.</p></div></EditorialSection><EditorialSection eyebrow="العلامات المتاحة" title="ما ستجده في الكتالوج"><div className="brand-list editorial-brand-list">{brands.map((brand) => { const product = catalog?.products.find((item) => item.brand === brand); return <Link className="brand-pill" href={`/brand/${product?.brandSlug || brand.toLowerCase().replace(/\s+/g, '-')}`} key={brand}>{brand}</Link>; })}</div></EditorialSection><EditorialSection title="منهج CABL في المحتوى"><div className="editorial-copy"><p>نبدأ من معلومات المنتج المنشورة، ثم نفصل بين المواصفة المعلنة والتقدير العملي. عندما تكون المعلومة غير متاحة، نذكر ذلك بدلاً من اختراع مدة ضمان أو نتيجة اختبار.</p><ul className="check-list"><li><Check size={16}/> المقارنة تعتمد على السعر والتوافق والمنافذ المتاحة.</li><li><Check size={16}/> العيوب والحدود جزء من وصف المنتج، وليست ملاحظة مخفية.</li><li><Check size={16}/> السعر والتوافر الحاليان يُؤخذان من الكتالوج وقت الطلب.</li></ul></div></EditorialSection><CTASection/></>;
}

export function ArticlePage() {
  const { catalog } = useStore();
  const powerProducts = (catalog?.products || []).filter((product) => `${product.productName} ${product.shortDescription || ''}`.toLowerCase().includes('باور')).slice(0, 5);
  return <><PageMeta title="دليل اختيار باور بانك" description="دليل CABL لفهم السعة والقدرة والمنافذ قبل شراء باور بانك في اليمن."/><EditorialHero eyebrow="دليل شراء" title="كيف تختار باور بانك يناسب يومك؟" description="لا تبدأ من رقم mAh وحده. قارن الطاقة والمنافذ والخرج والتوافق مع استخدامك الفعلي في اليمن."/><EditorialSection title="لماذا تحتاج باور بانك؟"><div className="editorial-copy"><p>انقطاع الكهرباء والتنقل الطويل والعمل من الهاتف يجعل الطاقة الاحتياطية جزءاً من اليوم. الاختيار الجيد ليس الأكبر دائماً؛ هو المنتج الذي يناسب جهازك ووزنك ومدة الاستخدام التي تحتاجها.</p></div><div className="numbered-steps"><div><b>01</b><h3>حدد الجهاز</h3><p>هاتف، تابلت، راوتر أو لابتوب؟ كل جهاز يحتاج قدرة ومخرجاً مختلفين.</p></div><div><b>02</b><h3>افهم السعة</h3><p>mAh تصف سعة الخلايا، بينما Wh تساعد على مقارنة الطاقة النظرية بين الموديلات.</p></div><div><b>03</b><h3>راجع الخرج</h3><p>طابق USB-C PD أو البروتوكول المطلوب مع الجهاز والكابل قبل الطلب.</p></div></div></EditorialSection><EditorialSection eyebrow="مقارنة عملية" title="اختيارات من الكتالوج"><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>المنتج</th><th>السعر</th><th>التوافر</th><th>التفاصيل</th></tr></thead><tbody>{powerProducts.map((product) => <tr key={product.id}><td>{product.productName}</td><td>{useStorePrice(product, catalog?.currencies)}</td><td>{product.quantity > 0 ? 'متوفر' : 'نفد حالياً'}</td><td><Link href={`/product/${product.slug}`} className="text-link">افتح المنتج <ArrowLeft size={14}/></Link></td></tr>)}</tbody></table></div></EditorialSection><EditorialSection title="نصائح قبل الشراء"><InfoCards items={[{ icon: <ShieldCheck/>, title: 'تحقق من المصدر', text: 'راجع العلامة والموديل والصور والبيانات داخل صفحة المنتج.' }, { icon: <Zap/>, title: 'لا تطارد أكبر رقم', text: 'القدرة الأكبر لا تفيد إذا كان جهازك أو الكابل لا يدعمانها.' }, { icon: <Package/>, title: 'احسب الاستخدام', text: 'اختر 10,000 للاستخدام الخفيف، و20,000 أو أكثر للرحلات والأحمال الأطول بعد مراجعة الوزن.' } ]}/></EditorialSection><EditorialSection title="أسئلة شائعة"><FAQList items={[{ question: 'هل mAh وحدها تكفي للمقارنة؟', answer: 'لا. قارن Wh إن كانت متاحة، ثم راجع قدرة الخرج والمنافذ والوزن والتوافق.' }, { question: 'هل كل باور بانك يشحن اللابتوب؟', answer: 'لا. يجب أن يذكر المنتج مخرج USB-C PD بقدرة مناسبة، وتحتاج إلى كابل مناسب.' }, { question: 'هل عدد الشحنات مضمون؟', answer: 'لا. عدد الشحنات تقديري ويتغير حسب فقد التحويل والجهاز والحرارة وطريقة الاستخدام.' }]}/></EditorialSection><CTASection/></>;
}

function useStorePrice(product: StoreProduct, currencies: Array<{ code: string; ratePerUsd: number; isDefault: boolean }> | undefined) {
  const currency = currencies?.find((item) => item.isDefault) || currencies?.[0];
  return new Intl.NumberFormat('ar-YE', { style: 'currency', currency: currency?.code || 'USD', maximumFractionDigits: 0 }).format((product.discountPrice ?? product.regularPrice) * (currency?.ratePerUsd || 1));
}

export function LocationPage() {
  const { catalog, formatPrice } = useStore();
  const { slug = 'yemen' } = useParams<{ slug: string }>();
  return <><PageMeta title="التوصيل داخل اليمن" description="معلومات الشحن والتوصيل داخل اليمن من CABL."/><EditorialHero eyebrow="التوصيل / اليمن" title="حلول شحن تصل إلى محافظتك" description={`راجع خيارات الشحن الحالية قبل تأكيد طلبك إلى ${slug === 'yemen' ? 'أي محافظة في اليمن' : slug}.`}><Link href="/checkout" className="button button-primary">ابدأ طلبك <ArrowLeft size={16}/></Link></EditorialHero><EditorialSection title="معلومات الطلب"><InfoCards items={(catalog?.shippingOptions || []).map((option) => ({ icon: <Truck/>, title: option.name, text: `${option.free ? 'بدون رسوم شحن' : `الرسوم الحالية ${formatPrice(option.charge)}`} — المدة التقديرية ${option.estimatedDays ? `${option.estimatedDays} أيام` : 'تؤكد مع الطلب'}.` }))}/></EditorialSection><EditorialSection title="كيف تختار الحل المناسب؟"><div className="numbered-steps"><div><b>01</b><h3>ابدأ من الجهاز</h3><p>الهاتف والتابلت واللابتوب والراوتر لا يحتاجون نفس القدرة أو الكابل.</p></div><div><b>02</b><h3>راجع العنوان</h3><p>أدخل المدينة والعنوان في checkout حتى تظهر طريقة الشحن الأنسب.</p></div><div><b>03</b><h3>أكد التفاصيل</h3><p>راجع السعر والشحن وطريقة الدفع قبل إرسال الطلب.</p></div></div></EditorialSection><EditorialSection title="أسئلة التوصيل"><FAQList items={[{ question: 'كم تستغرق مدة التوصيل؟', answer: 'المدة الظاهرة في checkout تقديرية حسب طريقة الشحن والعنوان، ويؤكد فريق الطلب التفاصيل عند المراجعة.' }, { question: 'هل الشحن مجاني؟', answer: 'تظهر الرسوم الفعلية من خيارات الشحن النشطة في قاعدة بيانات CABL، ولا نعتمد على حد مجاني مخترع.' }, { question: 'هل تصلون إلى كل المحافظات؟', answer: 'اختر المدينة والعنوان في الطلب؛ خيارات الشحن الحالية هي المرجع العملي للتغطية.' }]}/></EditorialSection><CTASection/></>;
}

export function SolutionPage() {
  const { catalog } = useStore();
  const products = (catalog?.products || []).filter((product) => `${product.productName} ${product.shortDescription || ''}`.toLowerCase().match(/سيارة|car|كابل|شاحن/)).slice(0, 4);
  return <><PageMeta title="حلول الشحن اليومية" description="حلول CABL لمشاكل الشحن والحرارة والبطارية أثناء الاستخدام اليومي."/><EditorialHero eyebrow="حل عملي" title="حل مشكلة الشحن البطيء في السيارة" description="ابدأ من شاحن سيارة USB-C مناسب، وكابل مصنف، واستخدام يقلل الحرارة أثناء الملاحة والتنقل."/><EditorialSection title="الحل التقني المقترح"><div className="editorial-copy"><p>شاحن سيارة USB-C مع دعم PD، وقدرة مناسبة للهاتف، أفضل من محول USB-A قديم لا يتفاوض مع الجهاز الحديث. الكابل جزء من الحل، وليس قطعة منفصلة عن القدرة.</p></div><div className="check-list large-checks"><div><Check size={18}/> استخدم شاحناً بقدرة تناسب تفاوض هاتفك.</div><div><Check size={18}/> استخدم كابل USB-C مصنفاً للقدرة المطلوبة.</div><div><Check size={18}/> خفّض السطوع وتجنب الشحن اللاسلكي عند ارتفاع الحرارة.</div><div><Check size={18}/> أوقف الشحن إذا استمر الاختناق الحراري.</div></div></EditorialSection><EditorialSection title="منتجات موصى بها من الكتالوج">{catalog ? <ProductGrid products={products} empty="لا توجد منتجات مرتبطة بهذا الحل حالياً."/> : <LoadingCatalog/>}</EditorialSection><EditorialSection title="أسئلة شائعة"><FAQList items={[{ question: 'هل USB-A يكفي للهاتف الحديث؟', answer: 'قد يشحن، لكنه لا يوفّر بالضرورة تفاوض USB-C PD المطلوب للسرعة والاستقرار.' }, { question: 'هل PPS ضروري؟', answer: 'PD هو الأساس، وPPS يفيد بعض أجهزة أندرويد. راجع ما يقبله هاتفك تحديداً.' }]}/></EditorialSection><CTASection/></>;
}

export function LabPage() {
  const { catalog, isLoading, isError } = useStore();
  const products = catalog?.products || [];
  return <><PageMeta title="مركز المواصفات" description="مركز CABL لفهم مواصفات المنتجات والحسابات والتوافق قبل الشراء."/><EditorialHero eyebrow="CABL LAB" title="مركز المواصفات قبل أن تختار" description="فهرس عملي لبيانات المنتجات المنشورة. نعرض ما يأتي من الكتالوج، ونفصل بين المواصفة المعلنة وأي تقدير توضيحي."/><EditorialSection title="فهرس المنتجات المنشورة">{isLoading ? <LoadingCatalog/> : isError ? <CatalogError retry={() => window.location.reload()}/> : <div className="comparison-table-wrap"><table className="comparison-table lab-table"><thead><tr><th>SKU</th><th>المنتج</th><th>القسم</th><th>التوافر</th><th>الصفحة</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td dir="ltr">{product.sku}</td><td>{product.productName}</td><td>{product.category?.name || 'إكسسوارات'}</td><td>{product.quantity > 0 ? 'متوفر' : 'غير متوفر'}</td><td><Link href={`/product/${product.slug}`} className="text-link">افتح <ExternalLink size={13}/></Link></td></tr>)}</tbody></table></div>}</EditorialSection><EditorialSection title="كيف نقرأ المواصفات؟"><InfoCards items={[{ icon: <FlaskConical/>, title: 'المصدر أولاً', text: 'القدرة والمنافذ والموديل تبدأ من المعلومات المنشورة للمنتج.' }, { icon: <Zap/>, title: 'الحساب منفصل عن القياس', text: 'أي حساب للطاقة أو عدد الشحنات تقديري، وليس نتيجة اختبار مخبرية.' }, { icon: <ShieldCheck/>, title: 'الحدود واضحة', text: 'لا نضيف ادعاء توافق أو ضمان إذا لم يظهر في بيانات المنتج.' } ]}/></EditorialSection><CTASection/></>;
}

export function VerifyPage() {
  const [serial, setSerial] = useState('');
  const [submitted, setSubmitted] = useState(false);
  return <><PageMeta title="التحقق من الضمان" description="راجع بيانات طلبك وشروط الضمان المنشورة لدى CABL."/><EditorialHero eyebrow="خدمة ما بعد الشراء" title="التحقق من سجل الضمان" description="أدخل رقم السيريال أو رقم المنتج الموجود على طلبك. لا نعرض نتيجة مصطنعة؛ نستخدم بيانات الطلب والمنتج المنشورة فقط."/><EditorialSection title="ابدأ التحقق"><form className="lookup-card warranty-form" onSubmit={(event: FormEvent) => { event.preventDefault(); setSubmitted(true); }}><label className="form-field"><span>رقم السيريال أو SKU</span><input value={serial} onChange={(event) => setSerial(event.target.value)} placeholder="مثلاً: CABL-..." required data-testid="input-warranty-serial"/></label><button className="button button-primary" type="submit" data-testid="button-warranty-submit">إرسال للمراجعة <ShieldCheck size={16}/></button>{submitted && <div className="notice" role="status">تم تسجيل الرقم للمراجعة. احتفظ برقم طلبك، ثم استخدم صفحة تتبع الطلب لعرض بيانات الشراء وشروط المنتج.</div>}</form></EditorialSection><EditorialSection title="ما الذي نتحقق منه؟"><InfoCards items={[{ icon: <Package/>, title: 'رقم الطلب', text: 'رقم الطلب يربط المنتج بالشراء الصحيح.' , href: '/orders' }, { icon: <ShieldCheck/>, title: 'شروط المنتج', text: 'مدة وشروط الضمان لا تُفترض؛ راجع ما يظهر في صفحة المنتج أو تأكيد الطلب.' }, { icon: <MessageCircle/>, title: 'مشكلة بعد الاستلام', text: 'اكتب وصف المشكلة ورقم الطلب حتى يمكن مراجعتها بوضوح.', href: '/contact' } ]}/></EditorialSection><CTASection/></>;
}

export function ShippingPage() {
  return <><PageMeta title="الشحن والتوصيل" description="سياسة الشحن والتوصيل الحالية في متجر CABL داخل اليمن."/><EditorialHero eyebrow="سياسة الشحن" title="الشحن والتوصيل" description="تعرف على مناطق التوصيل والمدة والرسوم قبل تأكيد الطلب."/><EditorialSection title="مناطق التوصيل"><div className="policy-list"><p><MapPin size={17}/> نخدم العناوين التي تظهر لها طريقة شحن نشطة في checkout داخل اليمن.</p><p><Check size={17}/> المدينة والعنوان يحددان الخيار المتاح والمدة التقديرية.</p><p><Check size={17}/> لا نعد بتغطية عنوان غير ظاهر في خيارات الشحن الحالية.</p></div></EditorialSection><EditorialSection title="المدة والتكلفة"><div className="policy-grid"><div><strong>المدة التقديرية</strong><p>تظهر بجانب طريقة الشحن قبل إرسال الطلب.</p></div><div><strong>الرسوم</strong><p>تظهر من قاعدة بيانات الشحن وبالعملة المختارة للعرض.</p></div><div><strong>الدفع</strong><p>تظهر طرق الدفع النشطة في checkout، ولا يتم إخفاء الخيار غير المتاح.</p></div></div></EditorialSection><EditorialSection title="قبل التأكيد"><div className="numbered-steps"><div><b>01</b><h3>راجع العنوان</h3><p>اكتب المدينة والعنوان بوضوح.</p></div><div><b>02</b><h3>قارن الخيارات</h3><p>اختر المدة والرسوم المناسبة.</p></div><div><b>03</b><h3>احتفظ بالرقم</h3><p>بعد إرسال الطلب، احفظ رقم الطلب للتتبع.</p></div></div></EditorialSection><CTASection/></>;
}

export function ReturnPage() {
  return <><PageMeta title="سياسة الإرجاع والاستبدال" description="الشروط والخطوات العامة للإرجاع والاستبدال في CABL."/><EditorialHero eyebrow="خدمة ما بعد الشراء" title="سياسة الإرجاع والاستبدال" description="راجع حالة المنتج والطلب قبل طلب الإرجاع، واحتفظ برقم الطلب وإثبات الشراء."/><EditorialSection title="مدة الإرجاع"><div className="policy-highlight"><strong>حسب الشروط المنشورة للمنتج والطلب</strong><span>تختلف الأهلية بحسب حالة المنتج وطريقة الشراء.</span></div></EditorialSection><EditorialSection title="شروط الإرجاع"><div className="check-list"><div><Check size={16}/> المنتج بحالته الأصلية وغير مستخدم.</div><div><Check size={16}/> التغليف والملحقات والكتيبات موجودة.</div><div><Check size={16}/> رقم الطلب أو إثبات الشراء متوفر.</div><div><Check size={16}/> لا يوجد تلف بسبب سوء الاستخدام أو التعديل.</div></div></EditorialSection><EditorialSection title="خطوات الإرجاع"><div className="numbered-steps"><div><b>01</b><h3>راجع الطلب</h3><p>افتح تفاصيل الطلب وتحقق من المنتج.</p></div><div><b>02</b><h3>اكتب المشكلة</h3><p>احتفظ بصور واضحة ووصف مختصر.</p></div><div><b>03</b><h3>انتظر المراجعة</h3><p>تؤكد الأهلية والخطوة التالية بعد مراجعة البيانات.</p></div></div></EditorialSection><EditorialSection title="المنتجات المعيبة"><div className="editorial-copy"><p>إذا وصل المنتج تالفاً أو مختلفاً عن الطلب، اذكر ذلك مباشرة مع رقم الطلب. بعد انتهاء فترة الإرجاع، تُراجع الحالة وفق شروط المنتج والضمان المنشورة.</p></div></EditorialSection><CTASection/></>;
}

export function FAQPage() {
  const items = [
    { question: 'كيف أقوم بالطلب؟', answer: 'تصفح الكتالوج، أضف المنتجات للسلة، أدخل بيانات العنوان واختر الشحن والدفع ثم أكد الطلب.' },
    { question: 'هل يمكن تعديل الطلب بعد إرساله؟', answer: 'استخدم رقم الطلب وتواصل عبر مسار الدعم المتاح قبل بدء التجهيز؛ إمكانية التعديل تعتمد على حالة الطلب.' },
    { question: 'كم تستغرق مدة التوصيل؟', answer: 'المدة التقديرية تظهر بجانب خيار الشحن، وقد تتغير بعد مراجعة المدينة والعنوان.' },
    { question: 'هل يمكنني تتبع طلبي؟', answer: 'نعم. افتح صفحة تتبع الطلب وأدخل البريد ورقم الهاتف المستخدمين عند الشراء.' },
    { question: 'هل المنتجات أصلية؟', answer: 'نعرض العلامة والموديل كما في بيانات المنتج. راجع الوصف والصور وشروط الضمان والإرجاع قبل التأكيد.' },
    { question: 'ما طرق الدفع المتاحة؟', answer: 'طرق الدفع النشطة تظهر في checkout من قاعدة بيانات CABL، مع تعليمات كل طريقة قبل إرسال الطلب.' },
    { question: 'هل أستطيع استخدام عملة أخرى؟', answer: 'نعم للعرض فقط؛ تظل حسابات الكتالوج والطلب بالدولار داخلياً كما هو موضح في الأسعار.' },
    { question: 'ماذا أفعل إذا وصل المنتج بمشكلة؟', answer: 'احتفظ برقم الطلب وصور المنتج والتغليف، ثم راجع سياسة الإرجاع وسجل المشكلة بوضوح.' },
  ];
  return <><PageMeta title="الأسئلة الشائعة" description="إجابات CABL عن الطلب والشحن والضمان والمنتجات والدفع."/><EditorialHero eyebrow="مساعدة سريعة" title="الأسئلة الشائعة" description="إجابات مباشرة على أكثر الأسئلة التي تظهر قبل وبعد شراء إكسسواراتك."/><EditorialSection title="الطلب والشحن والدفع"><FAQList items={items}/></EditorialSection><EditorialSection title="ما زلت تحتاج مساعدة؟"><div className="help-banner"><MessageCircle size={24}/><div><h3>ابدأ من بيانات طلب واضحة</h3><p>تصفح الكتالوج أو افتح صفحة تتبع الطلب، وستجد المعلومات المطلوبة في نفس المسار.</p></div><Link href="/orders" className="button button-primary">تتبع طلبك <ArrowLeft size={16}/></Link></div></EditorialSection><CTASection/></>;
}

export function ContactPage() {
  return <><PageMeta title="تواصل معنا" description="تواصل مع CABL حول الطلبات والمنتجات وخدمة ما بعد الشراء."/><EditorialHero eyebrow="CABL / خدمة العملاء" title="تواصل معنا" description="نساعدك من خلال بيانات الطلب والمنتج حتى تكون الإجابة مرتبطة بعملية شراء واضحة."/><EditorialSection title="بيانات الخدمة"><InfoCards items={[{ icon: <Package/>, title: 'عن طلب موجود', text: 'أدخل البريد ورقم الهاتف في صفحة التتبع لعرض الطلب.', href: '/orders' }, { icon: <BookOpen/>, title: 'قبل الشراء', text: 'اقرأ المواصفات ودليل الشراء قبل إضافة المنتج للسلة.', href: '/blog/best-power-bank-yemen' }, { icon: <RefreshCcw/>, title: 'إرجاع أو استبدال', text: 'راجع الشروط والخطوات قبل إرسال طلب المراجعة.', href: '/return-policy' } ]}/></EditorialSection><EditorialSection title="كيف تكتب طلب مساعدة مفيداً؟"><div className="check-list large-checks"><div><Check size={18}/> اذكر رقم الطلب إن كان موجوداً.</div><div><Check size={18}/> اكتب اسم المنتج أو SKU.</div><div><Check size={18}/> صف المشكلة ووقت ظهورها.</div><div><Check size={18}/> أرفق صور التغليف أو المنتج عند الحاجة.</div></div></EditorialSection><EditorialSection title="أسئلة متكررة"><FAQList items={[{ question: 'أين أجد بيانات المنتج؟', answer: 'في صفحة المنتج، أسفل السعر والتوافر والمواصفات.' }, { question: 'أين أجد بيانات الشحن والدفع؟', answer: 'في صفحة checkout وقسم السياسات، قبل تأكيد الطلب.' }, { question: 'كيف أتابع بعد الشراء؟', answer: 'من صفحة تتبع الطلب باستخدام البريد ورقم الهاتف.' }]}/></EditorialSection><CTASection/></>;
}

export function ProductEditorial({ product }: { product: StoreProduct }) {
  return <><EditorialSection eyebrow="تفاصيل الاستخدام" title="قبل أن تضغط تأكيد الطلب"><div className="product-editorial-grid"><div><h3>ما الذي نعرفه؟</h3><p>{product.shortDescription || 'بيانات أساسية منشورة في كتالوج CABL.'}</p></div><div><h3>ما الذي يجب مراجعته؟</h3><p>طابق المنفذ والقدرة والتوافق مع جهازك، ثم راجع التوافر والضمان والإرجاع الحاليين.</p></div><div><h3>الشحن والدفع</h3><p>تظهر خيارات الشحن والدفع النشطة في checkout قبل إرسال الطلب.</p></div></div></EditorialSection><EditorialSection title="أسئلة عن هذا المنتج"><FAQList items={[{ question: 'هل القدرة المعلنة تعني أن جهازي سيشحن بنفس السرعة؟', answer: 'لا. الجهاز والكابل والبروتوكول والحرارة تحدد القدرة الفعلية.' }, { question: 'هل المنتج متوفر الآن؟', answer: product.quantity > 0 ? `نعم، الكمية المنشورة حالياً ${product.quantity} قطعة.` : 'غير متوفر حالياً حسب الكمية المنشورة.' }, { question: 'أين أجد السعر النهائي؟', answer: 'السعر الحالي يظهر في الصفحة والسلة، وتضاف رسوم الشحن عند اختيار طريقة الشحن.' }]}/></EditorialSection></>;
}